// this is handmade crd & controller

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/trainyao/playground/k8s/crd-controller/handmade/pkg/client/clientset/versioned/typed/handmade/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeHandmadeV1 struct {
	*testing.Fake
}

func (c *FakeHandmadeV1) GoddessMoments(namespace string) v1.GoddessMomentInterface {
	return &FakeGoddessMoments{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeHandmadeV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
