// this is handmade crd & controller

// Code generated by lister-gen. DO NOT EDIT.

package v1

// GoddessMomentListerExpansion allows custom methods to be added to
// GoddessMomentLister.
type GoddessMomentListerExpansion interface{}

// GoddessMomentNamespaceListerExpansion allows custom methods to be added to
// GoddessMomentNamespaceLister.
type GoddessMomentNamespaceListerExpansion interface{}
