// this is handmade crd & controller

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	handmadev1 "github.com/trainyao/playground/k8s/crd-controller/handmade/pkg/apis/handmade/v1"
	versioned "github.com/trainyao/playground/k8s/crd-controller/handmade/pkg/client/clientset/versioned"
	internalinterfaces "github.com/trainyao/playground/k8s/crd-controller/handmade/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/trainyao/playground/k8s/crd-controller/handmade/pkg/client/listers/handmade/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GoddessMomentInformer provides access to a shared informer and lister for
// GoddessMoments.
type GoddessMomentInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.GoddessMomentLister
}

type goddessMomentInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGoddessMomentInformer constructs a new informer for GoddessMoment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGoddessMomentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGoddessMomentInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredGoddessMomentInformer constructs a new informer for GoddessMoment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGoddessMomentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HandmadeV1().GoddessMoments(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HandmadeV1().GoddessMoments(namespace).Watch(context.TODO(), options)
			},
		},
		&handmadev1.GoddessMoment{},
		resyncPeriod,
		indexers,
	)
}

func (f *goddessMomentInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGoddessMomentInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *goddessMomentInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&handmadev1.GoddessMoment{}, f.defaultInformer)
}

func (f *goddessMomentInformer) Lister() v1.GoddessMomentLister {
	return v1.NewGoddessMomentLister(f.Informer().GetIndexer())
}
