// this is handmade crd & controller

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/trainyao/playground/k8s/crd-controller/handmade/pkg/apis/handmade/v1"
	scheme "github.com/trainyao/playground/k8s/crd-controller/handmade/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GoddessMomentsGetter has a method to return a GoddessMomentInterface.
// A group's client should implement this interface.
type GoddessMomentsGetter interface {
	GoddessMoments(namespace string) GoddessMomentInterface
}

// GoddessMomentInterface has methods to work with GoddessMoment resources.
type GoddessMomentInterface interface {
	Create(ctx context.Context, goddessMoment *v1.GoddessMoment, opts metav1.CreateOptions) (*v1.GoddessMoment, error)
	Update(ctx context.Context, goddessMoment *v1.GoddessMoment, opts metav1.UpdateOptions) (*v1.GoddessMoment, error)
	UpdateStatus(ctx context.Context, goddessMoment *v1.GoddessMoment, opts metav1.UpdateOptions) (*v1.GoddessMoment, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.GoddessMoment, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.GoddessMomentList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.GoddessMoment, err error)
	GoddessMomentExpansion
}

// goddessMoments implements GoddessMomentInterface
type goddessMoments struct {
	client rest.Interface
	ns     string
}

// newGoddessMoments returns a GoddessMoments
func newGoddessMoments(c *HandmadeV1Client, namespace string) *goddessMoments {
	return &goddessMoments{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the goddessMoment, and returns the corresponding goddessMoment object, and an error if there is any.
func (c *goddessMoments) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.GoddessMoment, err error) {
	result = &v1.GoddessMoment{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("goddessmoments").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GoddessMoments that match those selectors.
func (c *goddessMoments) List(ctx context.Context, opts metav1.ListOptions) (result *v1.GoddessMomentList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.GoddessMomentList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("goddessmoments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested goddessMoments.
func (c *goddessMoments) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("goddessmoments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a goddessMoment and creates it.  Returns the server's representation of the goddessMoment, and an error, if there is any.
func (c *goddessMoments) Create(ctx context.Context, goddessMoment *v1.GoddessMoment, opts metav1.CreateOptions) (result *v1.GoddessMoment, err error) {
	result = &v1.GoddessMoment{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("goddessmoments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(goddessMoment).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a goddessMoment and updates it. Returns the server's representation of the goddessMoment, and an error, if there is any.
func (c *goddessMoments) Update(ctx context.Context, goddessMoment *v1.GoddessMoment, opts metav1.UpdateOptions) (result *v1.GoddessMoment, err error) {
	result = &v1.GoddessMoment{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("goddessmoments").
		Name(goddessMoment.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(goddessMoment).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *goddessMoments) UpdateStatus(ctx context.Context, goddessMoment *v1.GoddessMoment, opts metav1.UpdateOptions) (result *v1.GoddessMoment, err error) {
	result = &v1.GoddessMoment{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("goddessmoments").
		Name(goddessMoment.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(goddessMoment).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the goddessMoment and deletes it. Returns an error if one occurs.
func (c *goddessMoments) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("goddessmoments").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *goddessMoments) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("goddessmoments").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched goddessMoment.
func (c *goddessMoments) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.GoddessMoment, err error) {
	result = &v1.GoddessMoment{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("goddessmoments").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
